bloccipedia1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :subscribers
  resources :charges, only: [:new, :create]
  resources :wikis

  root 'welcome#index'

end

bloccipedia1/app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  before_save { self.role ||= :member }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :default_role

  enum role: [:member, :premium, :admin]

  def default_role
    self.role ||= :member
  end
end

bloccipedia1/app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
end

bloccipedia1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

bloccipedia1/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
     @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.username}",
     amount: Amount.default
   }
  end

  def create
  # Creates a Stripe Customer object, for associating
  # with the charge
    customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )

  # Where the real magic happens
  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- this is NOT the user_id in your app
    amount: Amount.default,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
  )

  flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
  redirect_to new_charge_path # or wherever

  # Stripe will send back CardErrors, with friendly messages
  # when something goes wrong.
  # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  class Amount
    def self.default
      15_00
    end
  end
end

bloccipedia1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  after_action :verify_authorized, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirects_to users_path
  end
end

bloccipedia1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

bloccipedia1/app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @wikis = Wiki.all
  end

  def create
     @wiki = Wiki.new
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]

     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
   end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def update
     @wiki = Wiki.find(params[:id])
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]

     if @wiki.save
       flash[:notice] = "wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
     end
  end

  def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

bloccipedia1/app/helpers/application_helper.rb
module ApplicationHelper
end

bloccipedia1/app/helpers/charges_helper.rb
module ChargesHelper
end

bloccipedia1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bloccipedia1/app/helpers/wikis_helper.rb
module WikisHelper
end

bloccipedia1/app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$15.00</strong>!</h2>

bloccipedia1/app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h3>Your Subscription </h3>
  <p> Your current subscription is: <%= current_user.role.capitalize%></p>
  <p> Update to Premium for $15<p>

  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

bloccipedia1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccipedia1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'applcation', "https://js.stripe.com/v2/" %>
    <%= tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key] %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li class="user-info"><%= link_to "Upgrade Account", new_charge_path %></li>
        <li class="user-info"><%= link_to "Bloccipedia", root_path %> </li>
        <li class="user-info"><%= link_to "Wikis", wikis_path %> </li>
        <li class="pull-right user-info">
          <% if user_signed_in? %>
            <div class="pull-right user-info">
               Signed in as: <strong><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link'  %></strong> |
               <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            </div>
          <% else %>
            <div class="user-info">
               <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
               <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %> -
            </div>
          <% end %>
        </li>
      </ul>
      <%= yield %>
    </div>
    <!-- <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script type="text/javascript">
      Stripe.setPublishableKey('pk_test_ogUopkCx8w7u3I0XWuamnezl');
    </script> -->
  </body>
</html>

bloccipedia1/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

bloccipedia1/app/views/users/show.html.erb
<br>
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#account">Account</a>
      </h4>
    </div>
    <div id="account" class="collapse in">
      <div class="panel-body">
        Username: <%= @user.username %>
        <br>
        Email: <%= @user.email %>
        <br>
        Status: <%= @user.role %>
        <% if @user.wiki.last  %>
          <div class="card">
            <div class="card-block">
              <h4 class="card-title">Last Wiki</h4>
              <p class="card-text"><%= link_to @user.wiki.last.title, wiki_path(@user.wiki.last.id) %></p>
              <sub>Created on: <%= @user.wiki.last.created_at %></sub>
            </div>
          </div>
        <% else %>
        <h5>You have not created a wiki yet.</h5>
        <%= link_to "Create Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#billing">Membership</a>
      </h4>
    </div>
    <div id="billing" class="collapse in">
      <div class="panel-body">
        <h5>Your current role is <%= @user.role %></h5>
        <h5>You may change your membership below.</h5>
        <div class="row">
          <% if @user.role != 'member' %>
            <div class="col-sm-6">
              <div class="card card-block">
                <h3 class="card-title">Standard</h3>
                <p class="card-text">Create and edit public Wiki's</p>
                <%= link_to "Free Account", subscriber_path(1), method: :delete, class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
          <% if @user.role != 'premium' %>
            <%= render partial: 'subscribers/subscribe', locals: { plan_id: '1002', role: 'premium', desc: "Create and edit private Wiki's.", price: '$15.99/month' } %>
          <% end %>
          <% if @user.role != 'admin' %>
            <%= render partial: 'subscribers/subscribe', locals: { plan_id: '1003', role: 'admin', desc: "No rules. God Mode.", price: '$99.99/month' } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

bloccipedia1/app/views/welcome/index.html.erb
<h4>Welcome to bloccipedia</h4>
<p>This is where you'll find a bunch of wikis on Twin Peaks </p>

bloccipedia1/app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

bloccipedia1/app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
 <div class="media">
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to wiki.title, wiki %>
     </h4>
   </div>
 </div>
<% end %>

bloccipedia1/app/views/wikis/new.html.erb
<<h1>New wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

bloccipedia1/app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @wiki.body %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>